# Generated by Django 5.1.4 on 2025-04-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="ntype",
            field=models.CharField(
                choices=[
                    ("NEW_PLAN_PURCHASED", "New Plan Purchased"),
                    ("PLAN_PURCHASE_FAILED", "Plan Purchase Failed"),
                    ("AMOUNT_REFUNDED", "Amount Refunded"),
                    ("PLAN_EXPIRED", "Plan Expired"),
                    ("BI_UPDATES", "Business Updates"),
                    ("BI_VERIFIED", "Business Verified"),
                    ("VISIT_REPORT", "Visit Report"),
                    ("ENQUIRY_REPORT", "Enquiry Report"),
                    ("BUISNESS_UPDATES", "Buisness Updates"),
                    ("PAYMENT_REMINDER", "Payment Reminder"),
                    ("PAYMENT_STATUS", "Payment Status"),
                ],
                default="BI_UPDATES",
                max_length=50,
            ),
        ),
    ]
