# Generated by Django 5.1.4 on 2025-04-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_alter_notification_ntype"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
