# Generated by Django 5.1.4 on 2025-02-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="District",
            new_name="City",
        ),
        migrations.RenameField(
            model_name="buisnesses",
            old_name="district",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="locality",
            old_name="Area_name",
            new_name="area_name",
        ),
        migrations.RenameField(
            model_name="locality",
            old_name="City",
            new_name="city",
        ),
    ]
