# Generated by Django 5.1.4 on 2025-04-14 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonepetransaction",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phonepe_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="phonepetransaction",
            index=models.Index(
                fields=["order_id"], name="usershome_p_order_i_4cd9c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonepetransaction",
            index=models.Index(fields=["status"], name="usershome_p_status_ed1fa5_idx"),
        ),
        migrations.AddIndex(
            model_name="phonepetransaction",
            index=models.Index(fields=["user"], name="usershome_p_user_id_7db0b2_idx"),
        ),
        migrations.AddIndex(
            model_name="phonepetransaction",
            index=models.Index(
                fields=["business"], name="usershome_p_busines_a40b6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonepetransaction",
            index=models.Index(
                fields=["created_at"], name="usershome_p_created_e93b56_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="phonepetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0.01)), name="amount_gte_0"
            ),
        ),
    ]
