# Generated by Django 5.1.4 on 2025-02-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "usershome",
            "0002_rename_district_city_rename_district_buisnesses_city_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="locality",
            old_name="area_name",
            new_name="locality_name",
        ),
    ]
