# Generated by Django 5.1.4 on 2025-04-15 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0002_alter_phonepetransaction_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonepetransaction",
            name="expire_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Expiration Time"
            ),
        ),
        migrations.AddField(
            model_name="phonepetransaction",
            name="payment_mode",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Payment Mode"
            ),
        ),
        migrations.AddField(
            model_name="phonepetransaction",
            name="phonepe_order_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="PhonePe Order ID"
            ),
        ),
        migrations.AddField(
            model_name="phonepetransaction",
            name="transction_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Transaction ID"
            ),
        ),
        migrations.AlterField(
            model_name="phonepetransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Amount (₹)",
            ),
        ),
        migrations.AlterField(
            model_name="phonepetransaction",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="phonepetransaction",
            name="order_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Transaction ID"
            ),
        ),
        migrations.AlterField(
            model_name="phonepetransaction",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Payment URL"
            ),
        ),
        migrations.AlterField(
            model_name="phonepetransaction",
            name="phonepe_callback",
            field=models.JSONField(blank=True, null=True, verbose_name="Callback Data"),
        ),
        migrations.AlterField(
            model_name="phonepetransaction",
            name="phonepe_response",
            field=models.JSONField(
                blank=True, null=True, verbose_name="PhonePe Response"
            ),
        ),
        migrations.AlterField(
            model_name="phonepetransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("INITIATED", "Initiated"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("EXPIRED", "Expired"),
                    ("REFUNDED", "Refunded"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
