# Generated by Django 5.1.4 on 2025-04-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0003_phonepetransaction_expire_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="phonepetransaction",
            name="usershome_p_busines_a40b6a_idx",
        ),
        migrations.RenameField(
            model_name="phonepetransaction",
            old_name="business",
            new_name="buisness",
        ),
        migrations.AddIndex(
            model_name="phonepetransaction",
            index=models.Index(
                fields=["buisness"], name="usershome_p_buisnes_9b114e_idx"
            ),
        ),
    ]
