# Generated by Django 5.1.4 on 2025-04-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0005_alter_auth_otps_otp_alter_email_otps_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonepetransaction",
            name="invoice",
            field=models.FileField(
                blank=True, null=True, upload_to="invoices/", verbose_name="Invoice"
            ),
        ),
    ]
