# Generated by Django 5.1.4 on 2025-04-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0006_phonepetransaction_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phonepetransaction",
            name="is_active",
        ),
    ]
