# Generated by Django 5.1.4 on 2025-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0006_buisnesses_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buisnesses",
            name="score",
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
