# Generated by Django 5.1.4 on 2025-04-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0007_remove_phonepetransaction_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="buisnesses",
            name="plan_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
