# Generated by Django 5.1.4 on 2025-02-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0008_alter_buisnesses_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buisnesses",
            name="score",
        ),
        migrations.AddField(
            model_name="buisnesses",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="Profile_pics/"
            ),
        ),
    ]
