# Generated by Django 5.1.4 on 2025-04-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0008_buisnesses_plan_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisness_offers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
