# Generated by Django 5.1.4 on 2025-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0009_buisness_offers_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="buisnesses",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="plans",
            name="business_hours",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plans",
            name="call",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plans",
            name="enquiry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plans",
            name="offers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plans",
            name="review_ratings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plans",
            name="social_meida",
            field=models.BooleanField(default=False),
        ),
    ]
