# Generated by Django 5.1.4 on 2025-04-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0010_buisnesses_created_at_plans_business_hours_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buisnesses",
            old_name="created_at",
            new_name="created_on",
        ),
    ]
