# Generated by Django 5.1.4 on 2025-05-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0011_rename_created_at_buisnesses_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_sub_category",
            name="general_cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcats",
                to="usershome.product_general_category",
            ),
        ),
    ]
