# Generated by Django 5.2 on 2025-04-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0010_plans_business_hours_plans_call_plans_enquiry_and_more'),
        ('usershome', '0011_rename_created_at_buisnesses_created_on'),
    ]

    operations = [
    ]
