# Generated by Django 5.1.4 on 2025-02-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0011_alter_buisnesses_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="buisnesses",
            name="score",
            field=models.CharField(default="15", max_length=12),
        ),
    ]
