# Generated by Django 5.1.4 on 2025-02-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0012_buisnesses_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buisnesses",
            name="no_of_views",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
