# Generated by Django 5.1.4 on 2025-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0013_alter_buisnesses_no_of_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="buisnesses",
            name="x_link",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="buisnesses",
            name="youtube_link",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
