# Generated by Django 5.1.4 on 2025-05-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0013_alter_product_sub_category_general_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="buisnesses",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
