# Generated by Django 5.1.4 on 2025-02-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0014_buisnesses_x_link_buisnesses_youtube_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="buisnesses",
            name="avg_time_spend_in_profile",
            field=models.CharField(default="15", max_length=50),
        ),
        migrations.AddField(
            model_name="buisnesses",
            name="email",
            field=models.EmailField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="buisnesses",
            name="no_of_enquiries",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="buisnesses",
            name="sa_rate",
            field=models.CharField(default="15", max_length=12),
        ),
    ]
