# Generated by Django 5.1.4 on 2025-05-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0014_buisnesses_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buisnesses",
            name="is_active",
        ),
    ]
