# Generated by Django 5.2.1 on 2025-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0015_remove_buisnesses_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='verbouse_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
