# Generated by Django 5.1.4 on 2025-02-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0015_buisnesses_avg_time_spend_in_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buisnesses",
            name="avg_time_spend_in_profile",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="buisnesses",
            name="score",
            field=models.CharField(default="0", max_length=12),
        ),
    ]
