# Generated by Django 5.1.4 on 2025-02-20 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0016_alter_buisnesses_avg_time_spend_in_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buisnesses",
            name="avg_time_spend_in_profile",
        ),
        migrations.RemoveField(
            model_name="buisnesses",
            name="no_of_views",
        ),
        migrations.CreateModel(
            name="BuisnessTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_spend", models.CharField(default="0", max_length=50)),
                ("date", models.DateField(auto_now=True)),
                (
                    "buisness",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usershome.buisnesses",
                    ),
                ),
            ],
        ),
    ]
