# Generated by Django 5.2.3 on 2025-06-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0017_alter_buisnesses_building_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews_ratings',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
