# Generated by Django 5.1.4 on 2025-02-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0017_remove_buisnesses_avg_time_spend_in_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buisnesses",
            name="no_of_views",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
