# Generated by Django 5.2.3 on 2025-06-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0018_reviews_ratings_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisnesses',
            name='target_audience_gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
