# Generated by Django 5.1.4 on 2025-02-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0018_buisnesses_no_of_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="searched",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="services",
            name="searched",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
