# Generated by Django 5.2.3 on 2025-06-21 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0019_buisnesses_target_audience_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessReviewTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('reviews_added_this_cycle', models.IntegerField(default=0)),
                ('cycle_start_date', models.DateField(default=django.utils.timezone.now)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usershome.buisnesses')),
            ],
        ),
    ]
