# Generated by Django 5.1.4 on 2025-02-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0019_products_searched_services_searched"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buisness_pics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="", upload_to="Photo_gallery/")),
                (
                    "buisness",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usershome.buisnesses",
                    ),
                ),
            ],
        ),
    ]
