# Generated by Django 5.1.4 on 2025-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0020_buisness_pics"),
    ]

    operations = [
        migrations.AddField(
            model_name="buisness_pics",
            name="description",
            field=models.CharField(default="", max_length=300),
        ),
    ]
