# Generated by Django 5.2.3 on 2025-06-22 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0020_businessreviewtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews_ratings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
