# Generated by Django 5.2.3 on 2025-06-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0021_alter_reviews_ratings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReviewSchedulerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
