# Generated by Django 5.1.4 on 2025-02-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0021_buisness_pics_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buisness_pics",
            name="description",
        ),
    ]
