# Generated by Django 5.2.3 on 2025-06-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0022_autoreviewschedulerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisnesses',
            name='qa_passed',
            field=models.BooleanField(default=False),
        ),
    ]
