# Generated by Django 5.2.3 on 2025-07-01 09:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0023_buisnesses_qa_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDirectTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount (₹)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Completed At')),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Mode')),
                ('buisness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_direct_transactions', to='usershome.buisnesses', verbose_name='Business')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_direct_transactions', to='usershome.plans', verbose_name='Subscription Plan')),
                ('plan_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_direct_transactions', to='usershome.plan_varients', verbose_name='Plan Variant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_direct_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
