# Generated by Django 5.1.4 on 2025-03-05 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0024_buisness_offers_liked_buisnesses_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liked_buisnesses",
            options={
                "verbose_name": "Liked Buisness",
                "verbose_name_plural": "Liked Buisnesses",
            },
        ),
        migrations.AlterField(
            model_name="liked_buisnesses",
            name="buisness",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_by_groups",
                to="usershome.buisnesses",
            ),
        ),
        migrations.AlterField(
            model_name="liked_buisnesses",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_businesses",
                to="usershome.liked_buisnesses_group",
            ),
        ),
        migrations.AlterField(
            model_name="liked_buisnesses_group",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="liked_buisnesses",
            unique_together={("buisness", "group")},
        ),
    ]
