# Generated by Django 5.2.3 on 2025-07-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0025_buisnessyoutubevideos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisnessyoutubevideos',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='usershome.buisnesses'),
        ),
    ]
