# Generated by Django 5.1.4 on 2025-03-07 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0025_alter_liked_buisnesses_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sitemap_Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=300)),
                ("buisness_getter", models.BooleanField(default=False)),
                ("cc_combination_getter", models.BooleanField(default=False)),
                (
                    "City",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usershome.city"
                    ),
                ),
                (
                    "buisness",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usershome.buisnesses",
                    ),
                ),
                (
                    "dcat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usershome.descriptive_cats",
                    ),
                ),
            ],
        ),
    ]
