# Generated by Django 5.1.4 on 2025-03-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0026_sitemap_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitemap_links",
            name="link",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
