# Generated by Django 5.2.3 on 2025-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0026_alter_buisnessyoutubevideos_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_otps',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
