# Generated by Django 5.2.3 on 2025-07-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0027_auth_otps_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_otps',
            old_name='admin',
            new_name='is_admin',
        ),
    ]
