# Generated by Django 5.1.4 on 2025-03-07 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0027_alter_sitemap_links_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitemap_links",
            name="City",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usershome.city",
            ),
        ),
        migrations.AlterField(
            model_name="sitemap_links",
            name="buisness",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usershome.buisnesses",
            ),
        ),
        migrations.AlterField(
            model_name="sitemap_links",
            name="dcat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usershome.descriptive_cats",
            ),
        ),
    ]
