# Generated by Django 5.1.4 on 2025-03-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0028_alter_sitemap_links_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitemap_links",
            old_name="buisness_getter",
            new_name="cc_combination",
        ),
        migrations.RenameField(
            model_name="sitemap_links",
            old_name="cc_combination_getter",
            new_name="single_buisness",
        ),
    ]
