# Generated by Django 5.1.4 on 2025-03-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usershome",
            "0029_rename_buisness_getter_sitemap_links_cc_combination_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="extended_user",
            name="is_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="extended_user",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
    ]
