# Generated by Django 5.1.4 on 2025-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0030_extended_user_is_customer_extended_user_is_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="buisness_offers",
            name="offer_type",
        ),
        migrations.AddField(
            model_name="buisness_offers",
            name="is_flat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="buisness_offers",
            name="is_percent",
            field=models.BooleanField(default=False),
        ),
    ]
