# Generated by Django 5.1.4 on 2025-03-12 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0033_buisnesses_landmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home_Meta_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(max_length=400, null=True)),
                ("meta_description", models.CharField(max_length=400, null=True)),
                ("meta_keywords", models.CharField(max_length=400, null=True)),
                ("meta_author", models.CharField(max_length=400, null=True)),
                ("page_title", models.CharField(max_length=400, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usershome.home_titles",
                    ),
                ),
            ],
        ),
    ]
