# Generated by Django 5.1.4 on 2025-03-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0034_home_meta_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home_meta_data",
            name="title",
        ),
    ]
