# Generated by Django 5.1.4 on 2025-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0035_remove_home_meta_data_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="home_meta_data",
            name="meta_og_description",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="home_meta_data",
            name="meta_og_image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="Home_pics/"
            ),
        ),
        migrations.AddField(
            model_name="home_meta_data",
            name="meta_og_image_alt",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="home_meta_data",
            name="meta_og_image_height",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="home_meta_data",
            name="meta_og_image_width",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="home_meta_data",
            name="meta_og_locale",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="home_meta_data",
            name="meta_og_site_name",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="home_meta_data",
            name="meta_og_title",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="home_meta_data",
            name="meta_og_type",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="home_meta_data",
            name="meta_og_url",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
