# Generated by Django 5.1.4 on 2025-03-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0036_home_meta_data_meta_og_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitemap_links",
            name="changefreq",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitemap_links",
            name="lastmod",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sitemap_links",
            name="priority",
            field=models.FloatField(default=0.5),
        ),
    ]
