# Generated by Django 5.1.4 on 2025-03-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0037_sitemap_links_changefreq_sitemap_links_lastmod_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitemap_links",
            old_name="City",
            new_name="city",
        ),
    ]
