# Generated by Django 5.1.4 on 2025-03-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0038_rename_city_sitemap_links_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitemap_links",
            name="meta_og_description",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="sitemap_links",
            name="meta_og_image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="Home_pics/"
            ),
        ),
        migrations.AddField(
            model_name="sitemap_links",
            name="meta_og_site_name",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="sitemap_links",
            name="meta_og_title",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="sitemap_links",
            name="meta_og_url",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="sitemap_links",
            name="buisness",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sitemap_link",
                to="usershome.buisnesses",
            ),
        ),
    ]
