# Generated by Django 5.1.4 on 2025-03-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0039_sitemap_links_meta_og_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitemap_links",
            old_name="changefreq",
            new_name="change_freq",
        ),
        migrations.RenameField(
            model_name="sitemap_links",
            old_name="lastmod",
            new_name="last_mod",
        ),
    ]
