# Generated by Django 5.1.4 on 2025-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0040_rename_changefreq_sitemap_links_change_freq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitemap_links",
            name="short_link",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
