# Generated by Django 5.1.4 on 2025-03-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0041_sitemap_links_short_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitemap_links",
            name="short_link",
        ),
        migrations.AddField(
            model_name="sitemap_links",
            name="share_link",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
