# Generated by Django 5.1.4 on 2025-03-12 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0042_remove_sitemap_links_short_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liked_buisnesses",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
