# Generated by Django 5.1.4 on 2025-03-12 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0043_liked_buisnesses_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mobile_number", models.CharField(max_length=15)),
                ("message", models.CharField(max_length=500)),
                ("date", models.DateField(auto_now=True)),
                ("time", models.TimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "buisness",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usershome.buisnesses",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
