# Generated by Django 5.1.4 on 2025-03-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0045_reviews_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews_ratings",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="Review_pics/"
            ),
        ),
    ]
