# Generated by Django 5.1.4 on 2025-03-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0046_reviews_ratings_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews_ratings",
            name="image",
        ),
        migrations.CreateModel(
            name="Review_pics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="", upload_to="Review_pics/")),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usershome.reviews_ratings",
                    ),
                ),
            ],
        ),
    ]
