# Generated by Django 5.1.4 on 2025-03-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0048_buisnesses_assured_buisnesses_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiries",
            name="message",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
