# Generated by Django 5.1.4 on 2025-03-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0049_alter_enquiries_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews_ratings",
            name="review",
            field=models.CharField(default="", max_length=500, null=True),
        ),
    ]
