# Generated by Django 5.1.4 on 2025-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0050_alter_reviews_ratings_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home_Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
