# Generated by Django 5.1.4 on 2025-03-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0053_buisnesses_rating_alter_liked_buisnesses_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="buisnesses",
            name="total_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
