# Generated by Django 5.1.4 on 2025-03-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0054_buisnesses_total_ratings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buisnesses",
            name="total_ratings",
        ),
    ]
