# Generated by Django 5.1.4 on 2025-03-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usershome", "0055_remove_buisnesses_total_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="buisnesses",
            name="total_no_of_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
