# Generated by Django 5.1.4 on 2025-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "accept_language",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("referer", models.URLField(blank=True, null=True)),
                ("origin", models.URLField(blank=True, null=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.TextField()),
                ("query_params", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
