# Generated by Django 5.1.4 on 2025-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Count_Per_Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buisness", models.IntegerField(default=0)),
                ("products", models.IntegerField(default=0)),
                ("services", models.IntegerField(default=0)),
                ("users", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
