"""
Django settings for brandsinfo project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-v)1y*)3ghutj1goo#r1yu*69l8$%3pr6#+8&4*3a(oy7mwq2pk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition



INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "usershome",
    'rest_framework',
    'django_elasticsearch_dsl'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',


]


ROOT_URLCONF = "brandsinfo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "brandsinfo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'brandsinfo',   
#         'USER': 'root',       
#         'PASSWORD': 'root123',  
#         'HOST': 'localhost',    
#         'PORT': '3306',         
#     }
# }




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'brandsinfo',   
        'USER': 'root',       
        'PASSWORD': 'Root@1234',  
        'HOST': 'localhost',    
        'PORT': '3306',         
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = "static/"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = 'usershome.Extended_User'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    'https://f509rzm8-3000.inc1.devtunnels.ms',

]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True





REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ),
   

}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'BLACKLIST_AFTER_ROTATION': True,
}


# dev
# ELASTICSEARCH_DSL = {
#     'default': {
#         'hosts': ['http://elastic:Z0NLsQ1r6OEnfGdTh2qr@localhost:9200/'],
#     },
# }



# production
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': ['http://elastic:tlTHrONRrteZRwDmhHoP@localhost:9200/'],
    },
}
    


MEDIA_URL = '/media/'  # URL path used to serve media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Directory where media files are stored
MAIN_CATEGORY_IMAGES_DIR = os.path.join(MEDIA_ROOT, 'Main_category_images')







EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'brandsinfoguide@gmail.com'  # Your Gmail account
EMAIL_HOST_PASSWORD = 'cpav vbda pjjk lmxs'  # App Password or Gmail password
DEFAULT_FROM_EMAIL = 'brandsinfoguide@gmail.com'  # Default from email (can be your Gmail or another verified email)






INSTALLED_APPS += ['channels']
ASGI_APPLICATION = "brandsinfo.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6380)],  # Redis Server
        },
    },
}


CELERY_BROKER_URL = "redis://127.0.0.1:6380/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'





# dev
# FRONTEND_BASE_URL_FOR_SM = 'https://45jfqx2q-3000.inc1.devtunnels.ms'
# BACKEND_BASE_URL_FOR_SM = 'https://mq459llx-8000.inc1.devtunnels.ms'
# BACKEND_BASE_URL_FOR_SM_SECURE = 'https://mq459llx-8000.inc1.devtunnels.ms'
# OPENAI_API_KEY='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'
# FAST2SMS_API_KEY='TNuYH9rIb5d7cM6UhWglVmB2vQEieXFKD314RJsStPCLGk08fAOnKw9RlTU30emkyMSD8uXqtfbJgcvW'

GEMINI_API_KEYS=[
                 'AIzaSyDwPLJew4URfzgMdQ43BEG-A7ldVs83_2w',    #gemini key in careindia
                'AIzaSyA5FqJy6E9Oypk0rp4FRezaFwvs7cd9dPc',    #icare key in icareindia

                 'AIzaSyAFMQMVZhQAsOBfTq36fdsBNnAJ0jl4nmo',    #gemini key in anjali
                 'AIzaSyATUTGsCNyIH4VW4bTfMRdoyiG--5KHV8o',  #brandsinfo key in anjali
                 
                 
                 'AIzaSyB2JQaUzhAB6fFlOgFB9DSmp8UAnBWOjvs',  # brandsinfo key in brandsinfo 
                
            
                 'AIzaSyDbM8NSNv49EX63BqC1alukSm0eS_8rtJ0', #gemini key in fightclub                
                'AIzaSyDmKDJSC2i7b_OST495c9HDnNIyJ4DPgGQ' #brandsinfo key in fightclub
                ]


# production
FRONTEND_BASE_URL_FOR_SM = 'https://brandsinfo.in'
BACKEND_BASE_URL_FOR_SM = 'https://api.brandsinfo.in'
BACKEND_BASE_URL_FOR_SM_SECURE = 'https://api.brandsinfo.in'
OPENAI_API_KEY='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'
FAST2SMS_API_KEY='TNuYH9rIb5d7cM6UhWglVmB2vQEieXFKD314RJsStPCLGk08fAOnKw9RlTU30emkyMSD8uXqtfbJgcvW'





FIREBASE_API_KEY = 'AIzaSyBF52Ah0ERtBRalBWwAOgEMPUhjKrlpVvo'
